import beefBurger from '../../assets/images/beef-burger.jpg';
import frenchFry from '../../assets/images/french-fries.svg';
import cheezeball from '../../assets/images/cheezeball.jpg';
import cheezestick from '../../assets/images/cheezestick.jpg';
import chickennuget from '../../assets/images/chickennugeets.png';
import ring from '../../assets/images/ring.jpg';
import strawberryIceCream from '../../assets/images/strawberryIceCream.jpg';
import chocoIceCream from '../../assets/images/choco-ice-cream.jpg';
import chickenPie from '../../assets/images/chicken-pie.jpg';
import friedChecken from '../../assets/images/fried-chicken.jpg';
import coke from '../../assets/images/coke.png';
import cider from '../../assets/images/cider.jpg';
import hotchoco from '../../assets/images/hotchoco.jpg';
import milk from '../../assets/images/milk.jpg';
import lemonade from '../../assets/images/lemonade.jpg';
import orangeJuice from '../../assets/images/orange-juice-67556_640.jpg';


export const categoryInformation = {
  recommended: [
    [
      {
        id: 0,
        src: beefBurger,
        name: '세트의정석 새우',
        price: 5900,
        setPrice: 5900,
        type: 'set',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 1,
        src: beefBurger,
        name: '2012 만원팩',
        price: 10000,
        setPrice: 10000,
        type: 'set',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 2,
        src: beefBurger,
        name: '새우버거',
        price: 3800,
        setPrice: 5800,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 3,
        src: beefBurger,
        name: '더블새우',
        price: 4500,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }
    ]
  ],
  hamburger: [
    [
      {
        id: 4,
        src: beefBurger,
        name: '치즈NO1',
        price: 4200,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 5,
        src: beefBurger,
        name: '네모새우',
        price: 4500,
        setPrice: 7500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 6,
        src: beefBurger,
        name: '한우불고기',
        price: 7200,
        setPrice: 9500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 7,
        src: beefBurger,
        name: '모짜렐라듬뿍버거',
        price: 6200,
        setPrice: 8500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 8,
        src: beefBurger,
        name: '와규에디션',
        price: 6000,
        setPrice: 9500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 9,
        src: beefBurger,
        name: '큰불',
        price: 5900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }
    ],
    [
      {
        id: 10,
        src: beefBurger,
        name: '폴더버거',
        price: 5800,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 11,
        src: beefBurger,
        name: '폴더버거 핫치킨',
        price: 5800,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 12,
        src: beefBurger,
        name: '모던치즈버거',
        price: 4400,
        setPrice: 5500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 13,
        src: beefBurger,
        name: '핫크리스피 버거',
        price: 4900,
        setPrice: 5500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 14,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 15,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }
    ],
    [
      {
        id: 16,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 17,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 18,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 19,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 20,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 21,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }
    ],
    [
      {
        id: 22,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 23,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 24,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 25,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 26,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 27,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }
    ],
  ],
  desert: [
    [
      {
        id: 28,
        src: chickennuget,
        name: '치킨너겟',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 29,
        src: frenchFry,
        name: '포테이토',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 30,
        src: cheezeball,
        name: '크림치즈볼',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 31,
        src: cheezestick,
        name: '치즈스틱',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 32,
        src: frenchFry,
        name: '양념감자',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 33,
        src: ring,
        name: '오징어링',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      }
    ],
    [
      {
        id: 34,
        src: frenchFry,
        name: '포테이토(L)',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 35,
        src: chocoIceCream,
        name: '초코초코',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 36,
        src: strawberryIceCream,
        name: '딸기딸기',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 37,
        src: friedChecken,
        name: '치킨1조각',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 38,
        src: chickenPie,
        name: 'F파이',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 39,
        src: chickenPie,
        name: '핫F파이',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
    ],
  ],
  drink: [
    [
      {
        id: 40,
        src: coke,
        name: '콜라',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 41,
        src: cider,
        name: '사이다',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 42,
        src: coke,
        name: '제로슈가콜라',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 43,
        src: coke,
        name: '콜라(L.라지)',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 44,
        src: cider,
        name: '사이다(L.라지)',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 45,
        src: coke,
        name: '제로슈가콜라(L.라지)',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      }
    ],
    [
      {
        id: 46,
        src: coke,
        name: '아메리카노',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 47,
        src: coke,
        name: '아이스아메리카노',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 48,
        src: coke,
        name: '카페라떼',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 49,
        src: milk,
        name: '우유',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 50,
        src: hotchoco,
        name: '핫초코',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 51,
        src: orangeJuice,
        name: '오렌지쥬스',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      }
    ],
    [
      {
        id: 52,
        src: lemonade,
        name: '레몬에이드',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
      {
        id: 54,
        src: lemonade,
        name: '레몬에이드(L)',
        price: 1200,
        setPrice: 0,
        type: 'single',
        orderCount: 0,
      },
    ],
  ],
  event: [[
    {
      id: 55,
      src: beefBurger,
      name: '한우불고기',
      price: 2000,
      setPrice: 4500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
    {
      id: 56,
      src: beefBurger,
      name: '모짜렐라듬뿍버거',
      price: 3200,
      setPrice: 4500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
    {
      id: 57,
      src: beefBurger,
      name: '와규에디션',
      price: 3000,
      setPrice: 4500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
    {
      id: 58,
      src: beefBurger,
      name: '큰불',
      price: 3900,
      setPrice: 4500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
    {
      id: 59,
      src: beefBurger,
      name: '폴더버거',
      price: 3800,
      setPrice: 4500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
  ]],
}
export const sideMenuInformation = {
  desert: [
    [
      {
        id: 0,
        type: 'desert',
        isSelected: false,
        name: "포테이토",
        price: 0,
        src: frenchFry,
      },
      {
        id: 1,
        type: 'desert',
        isSelected: false,
        name: '크림치즈볼',
        price: 400,
        src: cheezeball,
      },
      {
        id: 2,
        type: 'desert',
        isSelected: false,
        name: '치즈스틱',
        price: 500,
        src: cheezestick,
      },
      {
        id: 3,
        type: 'desert',
        isSelected: false,
        name: '양념감자',
        price: 500,
        src: frenchFry,
      },
      {
        id: 4,
        type: 'desert',
        isSelected: false,
        name: '오징어링',
        price: 700,
        src: ring,
      },
      {
        id: 5,
        type: 'desert',
        isSelected: false,
        name: '치킨너겟',
        price: 1000,
        src: chickennuget,
      },
      {
        id: 6,
        type: 'desert',
        isSelected: false,
        name: '포테이토(L)',
        price: 400,
        src: frenchFry,
      },
      {
        id: 7,
        type: 'desert',
        isSelected: false,
        name: '초코초코',
        price: 0,
        src: chocoIceCream,
      },
      {
        id: 8,
        type: 'desert',
        isSelected: false,
        name: '딸기딸기',
        price: 0,
        src: strawberryIceCream,
      },
      {
        id: 11,
        type: 'desert',
        isSelected: false,
        name: '치킨1조각',
        price: 800,
        src: friedChecken,
      },
      {
        id: 13,
        type: 'desert',
        isSelected: false,
        name: 'F파이',
        price: 1000,
        src: chickenPie,
      },
      {
        id: 14,
        type: 'desert',
        isSelected: false,
        name: '핫F파이',
        price: 1500,
        src: chickenPie,
      },
    ],
  ],

  drink: [
    [
      {
        id: 15,
        type: 'drink',
        isSelected: false,
        name: "콜라",
        price: 0,
        src: coke,
      },
      {
        id: 16,
        type: 'drink',
        isSelected: false,
        name: "사이다",
        price: 0,
        src: cider,
      },
      {
        id: 17,
        type: 'drink',
        isSelected: false,
        name: "제로슈가콜라",
        price: 0,
        src: coke,
      },
      {
        id: 18,
        type: 'drink',
        isSelected: false,
        name: "콜라(L.라지)",
        price: 200,
        src: coke,
      },
      {
        id: 19,
        type: 'drink',
        isSelected: false,
        name: "사이다(L.라지)",
        price: 200,
        src: cider,
      },
      {
        id: 20,
        type: 'drink',
        isSelected: false,
        name: "제로슈가콜라(L.라지)",
        price: 200,
        src: coke,
      },
      {
        id: 21,
        type: 'drink',
        isSelected: false,
        name: "아메리카노",
        price: 300,
        src: coke,
      },
      {
        id: 22,
        type: 'drink',
        isSelected: false,
        name: "아이스아메리카노",
        price: 300,
        src: coke,
      },
      {
        id: 23,
        type: 'drink',
        isSelected: false,
        name: "아이스아메리카노(L.라지)",
        price: 800,
        src: coke,
      },
      {
        id: 24,
        type: 'drink',
        isSelected: false,
        name: "카페라떼",
        price: 800,
        src: coke,
      },
      {
        id: 25,
        type: 'drink',
        isSelected: false,
        name: "우유",
        price: 0,
        src: milk,
      },
      {
        id: 26,
        type: 'drink',
        isSelected: false,
        name: "핫초코",
        price: 300,
        src: hotchoco,
      },
      {
        id: 27,
        type: 'drink',
        isSelected: false,
        name: "오렌지쥬스",
        price: 800,
        src: orangeJuice,
      },
      {
        id: 28,
        type: 'drink',
        isSelected: false,
        name: "레몬에이드",
        price: 800,
        src: lemonade,
      },
      {
        id: 29,
        type: 'drink',
        isSelected: false,
        name: "레몬에이드(L)",
        price: 1000,
        src: lemonade,
      }
    ],
  ]
}
