import beefBurger from '../../../assets/images/beef-burger.jpg';

export const CategoryInformation = {
  recommended: [
    [{
      id: 0,
      src: beefBurger,
      name: '세트의정석 새우',
      price: 5900,
      setPrice: 5900,
      type: 'set',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
      {
        id: 1,
        src: beefBurger,
        name: '2012 만원팩',
        price: 10000,
        setPrice: 10000,
        type: 'set',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 2,
        src: beefBurger,
        name: '새우버거',
        price: 3800,
        setPrice: 5800,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 3,
        src: beefBurger,
        name: '더블새우',
        price: 4500,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }]
  ],
  hamburger: [
    [{
      id: 4,
      src: beefBurger,
      name: '치즈NO1',
      price: 4200,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
      {
        id: 5,
        src: beefBurger,
        name: '네모새우',
        price: 4500,
        setPrice: 7500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 6,
        src: beefBurger,
        name: '한우불고기',
        price: 7200,
        setPrice: 9500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 7,
        src: beefBurger,
        name: '모짜렐라듬뿍버거',
        price: 6200,
        setPrice: 8500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 8,
        src: beefBurger,
        name: '와규에디션 2',
        price: 6000,
        setPrice: 9500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 9,
        src: beefBurger,
        name: '큰불',
        price: 5900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 10,
        src: beefBurger,
        name: '폴더버거 비프',
        price: 5800,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 11,
        src: beefBurger,
        name: '폴더버거 핫치킨',
        price: 5800,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }],
    [{
      id: 12,
      src: beefBurger,
      name: '모던치즈버거',
      price: 4400,
      setPrice: 5500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
      {
        id: 13,
        src: beefBurger,
        name: '핫크리스피 버거',
        price: 4900,
        setPrice: 5500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 14,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 15,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 16,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 17,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 18,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 19,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }],
    [{
      id: 20,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
      setOrderCount: 0,
      sideMenuList: [],
      sideMenuPrice: 0,
    },
      {
        id: 21,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 22,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 23,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 24,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 25,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 26,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      },
      {
        id: 27,
        src: beefBurger,
        name: '치즈NO 1',
        price: 4900,
        setPrice: 6500,
        type: 'single',
        orderCount: 0,
        setOrderCount: 0,
        sideMenuList: [],
        sideMenuPrice: 0,
      }],
  ],
  desert: [
    [{
      id: 28,
      src: beefBurger,
      name: '치킨너겟',
      price: 1200,
      setPrice: 0,
      type: 'single',
      orderCount: 0,
    }],
  ],
  drink: [
    [{
      id: 29,
      src: beefBurger,
      name: '치킨너겟',
      price: 1200,
      setPrice: 0,
      type: 'single',
      orderCount: 0,
    }],
  ],
  event: [],
}
export const sideMenuInformation = {
  desert: [
    [
      {
        id: 0,
        type: 'desert',
        isSelected: false,
        name: "포테이토",
        price: 0,
        src: beefBurger,
      },
      {
        id: 1,
        type: 'desert',
        isSelected: false,
        name: '모짜크림치즈볼',
        price: 400,
        src: beefBurger,
      },
      {
        id: 2,
        type: 'desert',
        isSelected: false,
        name: '치즈스틱',
        price: 500,
        src: beefBurger,
      },
      {
        id: 3,
        type: 'desert',
        isSelected: false,
        name: '양념감자',
        price: 500,
        src: beefBurger,
      },
      {
        id: 4,
        type: 'desert',
        isSelected: false,
        name: '오징어링',
        price: 700,
        src: beefBurger,
      },
      {
        id: 5,
        type: 'desert',
        isSelected: false,
        name: '치킨너겟',
        price: 1000,
        src: beefBurger,
      },
      {
        id: 6,
        type: 'desert',
        isSelected: false,
        name: '포테이토(L)',
        price: 400,
        src: beefBurger,
      },
      {
        id: 7,
        type: 'desert',
        isSelected: false,
        name: '초코초코',
        price: 0,
        src: beefBurger,
      },
      {
        id: 8,
        type: 'desert',
        isSelected: false,
        name: '딸기딸기',
        price: 0,
        src: beefBurger,
      },
      {
        id: 9,
        type: 'desert',
        isSelected: false,
        name: '토네이도 딸기',
        price: 1000,
        src: beefBurger,
      },
      {
        id: 10,
        type: 'desert',
        isSelected: false,
        name: '토네이도 쿠키',
        price: 1000,
        src: beefBurger,
      },
      {
        id: 11,
        type: 'desert',
        isSelected: false,
        name: '치킨1조각',
        price: 800,
        src: beefBurger,
      },
      {
        id: 12,
        type: 'desert',
        isSelected: false,
        name: '화이어링',
        price: 1000,
        src: beefBurger,
      },
      {
        id: 13,
        type: 'desert',
        isSelected: false,
        name: 'F파이',
        price: 1000,
        src: beefBurger,
      },
      {
        id: 14,
        type: 'desert',
        isSelected: false,
        name: '핫F파이',
        price: 1500,
        src: beefBurger,
      }
    ],
    [
      {
        id: 15,
        type: 'desert',
        isSelected: false,
        name: '휠렛치킨',
        price: 1500,
        src: beefBurger,
      },
      {
        id: 16,
        type: 'desert',
        isSelected: false,
        name: '바닐라아이스크림',
        price: 300,
        src: beefBurger,
      },
      {
        id: 17,
        type: 'desert',
        isSelected: false,
        name: '수박아이스크림',
        price: 300,
        src: beefBurger,
      }
    ]
  ],

  drink: [
    [
      {
        id: 15,
        type: 'drink',
        isSelected: false,
        name: "콜라",
        price: 0,
        src: beefBurger,
      },
      {
        id: 16,
        type: 'drink',
        isSelected: false,
        name: "사이다",
        price: 0,
        src: beefBurger,
      },
      {
        id: 17,
        type: 'drink',
        isSelected: false,
        name: "제로슈가콜라",
        price: 0,
        src: beefBurger,
      },
      {
        id: 18,
        type: 'drink',
        isSelected: false,
        name: "콜라(L.라지)",
        price: 200,
        src: beefBurger,
      },
      {
        id: 19,
        type: 'drink',
        isSelected: false,
        name: "사이다(L.라지)",
        price: 200,
        src: beefBurger,
      },
      {
        id: 20,
        type: 'drink',
        isSelected: false,
        name: "제로슈가콜라(L.라지)",
        price: 200,
        src: beefBurger,
      },
      {
        id: 21,
        type: 'drink',
        isSelected: false,
        name: "아메리카노",
        price: 300,
        src: beefBurger,
      },
      {
        id: 22,
        type: 'drink',
        isSelected: false,
        name: "아이스아메리카노",
        price: 300,
        src: beefBurger,
      },
      {
        id: 23,
        type: 'drink',
        isSelected: false,
        name: "아이스아메리카노(L.라지)",
        price: 800,
        src: beefBurger,
      },
      {
        id: 24,
        type: 'drink',
        isSelected: false,
        name: "카페라떼",
        price: 800,
        src: beefBurger,
      },
      {
        id: 25,
        type: 'drink',
        isSelected: false,
        name: "우유",
        price: 0,
        src: beefBurger,
      },
      {
        id: 26,
        type: 'drink',
        isSelected: false,
        name: "핫초코",
        price: 300,
        src: beefBurger,
      },
      {
        id: 27,
        type: 'drink',
        isSelected: false,
        name: "오렌지쥬스",
        price: 800,
        src: beefBurger,
      },
      {
        id: 28,
        type: 'drink',
        isSelected: false,
        name: "레몬에이드",
        price: 800,
        src: beefBurger,
      },
      {
        id: 29,
        type: 'drink',
        isSelected: false,
        name: "레몬에이드(L)",
        price: 1000,
        src: beefBurger,
      }
    ],
    [
      {
        id: 30,
        type: 'drink',
        isSelected: false,
        name: "딸기라떼",
        price: 0,
        src: beefBurger,
      },
      {
        id: 31,
        type: 'drink',
        isSelected: false,
        name: "아이시스",
        price: 0,
        src: beefBurger,
      },
      {
        id: 32,
        type: 'drink',
        isSelected: false,
        name: "아이스티",
        price: 0,
        src: beefBurger,
      }
    ]
  ]
}

export const initSideMenuState = () => {
  const {desert, drink} = sideMenuInformation;
  desert.forEach((menus) => {
    menus.forEach((menu) => {
      menu.isSelected = false;
    });
  });
  drink.forEach((menus) => {
    menus.forEach((menu) => {
      menu.isSelected = false;
    });
  });
}
