import beefBurger from '../../../assets/images/beef-burger.jpg';

export const CategoryInformation = {
  recommended: [
    [{
      id: 0,
      src: beefBurger,
      name: '세트의정석 새우',
      price: 5900,
      setPrice: 5900,
      type: 'set',
      orderCount: 0,
    },
    {
      id: 1,
      src: beefBurger,
      name: '2012 만원팩',
      price: 10000,
      setPrice: 10000,
      type: 'set',
      orderCount: 0,
    },
    {
      id: 2,
      src: beefBurger,
      name: '새우버거',
      price: 3800,
      setPrice: 5800,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 3,
      src: beefBurger,
      name: '더블새우',
      price: 4500,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    }]
  ],
  hamburger: [
    [{
      id: 4,
      src: beefBurger,
      name: '치즈NO1',
      price: 4200,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 5,
      src: beefBurger,
      name: '네모새우',
      price: 4500,
      setPrice: 7500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 6,
      src: beefBurger,
      name: '한우불고기',
      price: 7200,
      setPrice: 9500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 7,
      src: beefBurger,
      name: '모짜렐라듬뿍버거',
      price: 6200,
      setPrice: 8500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 8,
      src: beefBurger,
      name: '와규에디션 2',
      price: 6000,
      setPrice: 9500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 9,
      src: beefBurger,
      name: '큰불',
      price: 5900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 10,
      src: beefBurger,
      name: '폴더버거 비프',
      price: 5800,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 11,
      src: beefBurger,
      name: '폴더버거 핫치킨',
      price: 5800,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    }],
    [{
      id: 12,
      src: beefBurger,
      name: '모던치즈버거',
      price: 4400,
      setPrice: 5500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 13,
      src: beefBurger,
      name: '핫크리스피 버거',
      price: 4900,
      setPrice: 5500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 14,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 15,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 16,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 17,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 18,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 19,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    }],
    [{
      id: 20,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 21,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 22,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 23,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 24,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 25,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 26,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    },
    {
      id: 27,
      src: beefBurger,
      name: '치즈NO 1',
      price: 4900,
      setPrice: 6500,
      type: 'single',
      orderCount: 0,
    }],
  ],
  desert: [
    [{
      id: 28,
      src: beefBurger,
      name: '치킨너겟',
      price: 1200,
      setPrice: 0,
      type: 'single',
      orderCount: 0,
    }],
  ],
  drink: [
    [{
      id: 29,
      src: beefBurger,
      name: '치킨너겟',
      price: 1200,
      setPrice: 0,
      type: 'single',
      orderCount: 0,
    }],
  ],
  event: [],
}
